[package]
name = "easyeffects-chooser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyrun-plugin = { git = "https://github.com/Kirottu/anyrun" }
abi_stable = "0.11.1"
serde_json = "1.0.118"
serde = { version = "1.0.203", features = ["derive"] }
